(subdir
.
(dirs util datalog)
(rocq.theory
(modules :standard \ datalog.Local datalog.JSON datalog.QueryableToRunnable datalog.FancyNotations datalog.ForwardingNode)
(name Datalog)
(package datalog)
(theories Stdlib JSON ExtLib coqutil GraphSearch)
(generate_project_file)))
(include_subdirs qualified)
