name: Build Coq Code

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set workspace permissions for Docker
        run: |
          sudo chown -R 1000:1000 .

      - name: Compile with Rocq 9.0.0
        uses: coq-community/docker-coq-action@v1
        with:
          custom_image: rocq/rocq-prover:9.0.0
          custom_script: |
            startGroup "Rocq version"
              rocq --version
            endGroup
            startGroup "Compile"
              make
            endGroup
