name: Build Coq Code

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Coq
        run: |
          sudo apt-get update
          sudo apt-get install -y coq

      - name: Compile
        run: make
